.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     From: @(#)routed.8	6.6 (Berkeley) 3/16/91
.\"	From: @(#)routed.8	8.2 (Berkeley) 12/11/93
.\"	From: NetBSD: routed.8,v 1.6 1995/03/18 15:00:38 cgd Exp
.\"	Id: routed.8,v 1.3 1996/11/25 16:37:43 dholland Exp 
.\"
.\" This manpage was extracted from routed.8 by Steve Kostecke,
.\" <steve@debian.org>, for the Debian GNU/Linux System on
.\" July 5, 1999.
.\"
.TH GATEWAYS 5 "5 July 1999" "Debian" "Debian GNU/Linux Manual"
.SH NAME
gateways \- File which lists gateways for routed
.SH "DESCRIPTION"
.B /etc/gateways
.SM
is used by
.BR routed (8);
the file contains a list of gateways which may not be located by
using only information from the SIOGIFCONF
.BR ioctl (2)
when 
.BR routed (8)
is started.
.PP
Gateways specified in
.B /etc/gateways
should be marked passive
if they are not expected to exchange routing information,
while gateways marked active
should be willing to exchange routing information (i.e.
they should have a
.BR routed (8)
process running on the machine).
Routes through passive gateways are installed in the
kernel's routing tables once upon startup.
Such routes are not included in
any routing information transmitted.
Active gateways are treated equally to network
interfaces.  Routing information is distributed
to the gateway and if no routing information is
received for a period of time, the associated
route is deleted.
Gateways marked
.I external
are also passive, but are not placed in the kernel
routing table nor are they included in routing updates.
The function of external entries is to inform
.BR routed (8)
that another routing process
will install such a route, and that alternate routes to that
destination should not be installed. Such entries are only
required when both routers may learn of routes to the same
destination.
.PP
.B /etc/gateways
is comprised of a series of lines, each in the following format:
.PP
.RB "[ " "net " "| " "host " "]"
.IB "name1 " "gateway " "name2 " "metric " "value"
.RB "[ " "passive " "| " "active " "| " "external " "]"
.PP
The 
.B net
or
.B host
keyword indicates if the route is to a network or specific host.
.PP
.I Name1
is the name of the destination network or host.  This may be a
symbolic name located in
.I /etc/networks
or
.I /etc/hosts
(or, if started after
.BR named (8),
known to the name server), 
or an Internet address specified in ``dot'' notation; see
.BR inet (3).
.PP
.I Name2
is the name or address of the gateway to which messages should
be forwarded.
.PP
.I Value
is a metric indicating the hop count to the destination host
or network.
.PP
One of the keywords
.BR passive,
.B active
or
.B external
indicates if the gateway should be treated as 
.I passive
or
.I active
(as described above),
or whether the gateway is
.I external
to the scope of the
.BR routed (8)
protocol.
.PP
Internetwork routers that are directly attached to the Arpanet
or Milnet should use the Exterior Gateway Protocol EGP to gather
routing information rather then using a static routing table of
passive gateways. EGP is required in order to provide routes for
local networks to the rest of the Internet system.
.SH FILES
.I /etc/gateways
.SH SEE ALSO
.IR "Internet Transport Protocols", 
XSIS 028112, Xerox System Integration Standard,
.BR routed (8).
.SH HISTORY
The
.BR routed (8)
command appeared in 4.2BSD.
.SH AUTHOR
This manpage was extracted from 
.BR routed (8)
by Steve Kostecke, <steve@debian.org>, for the Debian GNU/Linux system.
