.TH ifupdown 8 "February 13, 2000"
.SH NAME
ifup \- bring a network interface up
.PP
ifdown \- take a network interface down
.SH SYNOPSIS
.B ifup 
.BI "[-sinv] [--scheme=" scheme "] [--interfaces=" file "] [--no-act]"
.BI "[--verbose] [-a|" ifaces "]"
.PP
.B ifdown
.BI "[-sinv] [--scheme=" scheme "] [--interfaces=" file "] [--no-act]"
.BI "[--verbose] [-a|" ifaces "]"
.SH DESCRIPTION
The
.BR ifup " and " ifdown
commands man be used to configure (or, respectively, deconfigure) network
interfaces, based on descriptions of the interfaces entered into the file
.IR /etc/network/interfaces .
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B "-h, --help"
Show summary of options.
.TP
.B "-v, --verbose"
Show commands being executed.
.TP
.B "-n, --no-act"
Don't actually execute the commands.
.TP
.BR "-i" " file" ", --interfaces" " file"
Read interface definitions from a different file.
.TP
.BR "-s" " scheme" ", --scheme" " scheme"
Use a particular scheme.
.TP
.B \-a, \-\-all
Affect all interfaces (except those marked \fBnoauto\fP).
.SH NOTES
The
.BR ifup " and " ifdown
programs don't actually know anything about configuring interfaces themselves
but instead invoke lower-level utilities such as
.BR ifconfig " and " route
to do the actual dirtywork. The main advantages to using
.BR ifup " and " ifdown
instead of calling the lower-level utilities directy is the ability to
keep all your interface specifications in a single (easily parsable) file,
and to not have to deal with the various idiosyncracies of the lower-level
commands.
.SH FILES
.TP
.B /etc/network/interfaces
Descriptions of all the network interfaces the system has.
.SH BUGS
Schemes as implemented (and as almost completely undocumented) are
something of a kludge, and will be significantly reworked in a future
version.
.SH AUTHOR
This manual page was written by Anthony Towns <aj@azure.humbug.org.au>.
.SH SEE ALSO
.BR interfaces (5),
.BR ifconfig (8),
