#!/bin/sh
# post remove script for the Debian GNU/Linux netbase package

set -e

if [ "$1" = "purge" ]
then
  update-rc.d networking remove >/dev/null
  update-rc.d inetd remove >/dev/null
  update-rc.d portmap remove >/dev/null

  if [ -L /sbin/ipfwadm ]; then
    rm /sbin/ipfwadm
  fi
fi

#DEBHELPER#
